version: '3.7'
x-app_common:
  &app_common
  build:
    context: ../../
    dockerfile: ops/dev/Dockerfile
  env_file:
    - app_env
    - app_env.secrets
  stdin_open: true
  tty: true
  volumes:
    - app_data:/app:cached
  ports:
    - 3000
  tmpfs:
    - /tmp

services:
  app:
    << : *app_common
    environment:
      VIRTUAL_HOST: demarches-simplifiees.syn,localhost
      VIRTUAL_PORT: 3000
  vite:
    << : *app_common
    command: ./bin/bun_vite dev
  delayed_job:
    << : *app_common
    command: rake jobs:work
  sidekiq:
    <<: *app_common
    command: bundle exec sidekiq

volumes:
  app_data:
    driver_opts:
      type: none
      device: "${PWD}/../../"
      o: bind

networks:
  default:
    name: plungy_default
