include:
  - project: ouidou/ci-templates
    ref: 0.3.3
    file: rails/.gitlab-ci-template.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  NODE_ENV: production
  WITH_ASSETS: "1"
  WITH_BRAKEMAN: "1"
  WITH_BUNDLE_AUDIT: "1"
  WITH_RAILS_BEST_PRACTICES: "1"
  WITH_REEK: "1"
  WITH_REVIEW: "0"
  WITH_RUBOCOP: "1"

default:
  interruptible: true

prepare:
  variables:
    PACKAGE: ops/ci/base/packages.txt
    RAILS_VERSION: ruby3.2.2-rails7.0.5

staging:adullact:
  extends: [deploy_staging]
  variables:
    CUSTOM_ASSETS_IMAGE: adullact-0.8.2.rc19
    ENV_NAME: staging
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.2.0
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: adullact-ds-staging
    PATH_VALUE: adullact/
    PREFIX_APP_NAME: adullact-ds
    SKIP_RESTORE_STAGE: "true"
    URL_STAGING: adullact-ds.staging.ouidou.fr

staging:somme-numerique:
  extends: [deploy_staging]
  variables:
    APP_VERSION: 1.5.5
    ASSETS_VERSION: 1.5.5
    CUSTOM_ASSETS_VERSION: somme-numerique-0.8.2.rc21
    ENV_NAME: somme-numerique-staging
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.2.0
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: sm-staging
    PATH_VALUE: somme-numerique/
    RELEASE_NAME: sm-staging
    SKIP_RESTORE_STAGE: "true"
    URL_STAGING: preprod.demarches-hdf.fr

production:adullact:
  extends: [deploy_production]
  variables:
    APP_VERSION: 1.5.5
    ASSETS_VERSION: 1.5.5
    CUSTOM_ASSETS_VERSION: adullact-0.8.2.rc19
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.2.0
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: adullact-ds-staging
    PATH_VALUE: adullact/
    RELEASE_NAME: adullact-production-demarches-simplifiees
    SKIP_RESTORE_STAGE: "true"
    URL_PRODUCTION: demarches-simplifiees.com

production:gironde-numerique:
  extends: [deploy_production]
  variables:
    APP_VERSION: 1.1.0
    ASSETS_VERSION: 1.1.0
    ENV_NAME: gironde-numerique
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.2.0
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: production
    PATH_VALUE: gironde-numerique/
    RELEASE_NAME: gn-production
    SKIP_RESTORE_STAGE: "true"
    URL_PRODUCTION: demarches.girondenumerique.fr

production:somme-numerique:
  extends: [deploy_production]
  variables:
    APP_VERSION: 1.5.5
    ASSETS_VERSION: 1.5.5
    CUSTOM_ASSETS_VERSION: somme-numerique-0.8.2.rc21
    ENV_NAME: somme-numerique
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.2.0
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: sm-production
    PATH_VALUE: somme-numerique/
    RELEASE_NAME: sm-production
    SKIP_RESTORE_STAGE: "true"
    URL_PRODUCTION: demarches-hdf.fr
