include:
  - project: ouidou/ci-templates
    ref: 0.5.0
    file: rails/.gitlab-ci-template.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_UPDATE_FLAGS: --remote
  GIT_SUBMODULE_FORCE_HTTPS: "true"
  NODE_ENV: production
  WITH_ASSETS: "1"
  WITH_BRAKEMAN: "1"
  WITH_BUNDLE_AUDIT: "1"
  WITH_RAILS_BEST_PRACTICES: "1"
  WITH_REEK: "1"
  WITH_REVIEW: "0"
  WITH_RUBOCOP: "1"
  WITH_SONAR: "0"

default:
  interruptible: true

prepare:
  variables:
    PACKAGE: ops/ci/base/packages.txt
    RAILS_VERSION: ruby3.3.0-rails7.0.8

compile_assets:
  script:
    - bundle check # workaround for mimemagic not found
    - set -a
    - source ${CI_PROJECT_DIR}/ops/ci/release/assets/app_env
    - bun install
    - echo "ASSETS_COMMAND is $ASSETS_COMMAND"
    - eval "$ASSETS_COMMAND"

# We look for values.yml in ${ENV_NAME}/${PATH_VALUE}
staging:adullact:
  extends: [deploy_staging]
  variables:
    CUSTOM_ASSETS_IMAGE: adullact-0.8.2.rc24
    ENV_NAME: staging
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.4.1
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: adullact-ds-staging
    PATH_VALUE: adullact/
    PREFIX_APP_NAME: adullact-ds
    SKIP_RESTORE_STAGE: "true"
    URL_STAGING: adullact-ds.staging.ouidou.fr

staging:somme-numerique:
  extends: [deploy_staging]
  variables:
    CUSTOM_ASSETS_VERSION: somme-numerique-0.8.2.rc24
    ENV_NAME: somme-numerique-staging
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.4.1
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: sm-staging
    PATH_VALUE: somme-numerique/
    RELEASE_NAME: sm-staging
    SKIP_RESTORE_STAGE: "true"
    URL_STAGING: preprod.demarches-hdf.fr

production:adullact:
  extends: [deploy_production]
  variables:
    APP_VERSION: 1.5.7.rc8
    ASSETS_VERSION: 1.5.7.rc8
    CUSTOM_ASSETS_VERSION: adullact-0.8.2.rc24
    ENV_NAME: adullact
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.4.1
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: adullact-ds-production
    PATH_VALUE: adullact/
    RELEASE_NAME: production
    SKIP_RESTORE_STAGE: "true"
    URL_PRODUCTION: demarches.adullact.org

production:gironde-numerique:
  extends: [deploy_production]
  variables:
    APP_VERSION: 1.1.0
    ASSETS_VERSION: 1.1.0
    ENV_NAME: gironde-numerique
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.2.1
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: production
    PATH_VALUE: gironde-numerique/
    RELEASE_NAME: gn-production
    SKIP_RESTORE_STAGE: "true"
    URL_PRODUCTION: demarches.girondenumerique.fr

production:somme-numerique:
  extends: [deploy_production]
  variables:
    APP_VERSION: 1.5.7.rc9
    ASSETS_VERSION: 1.5.7.rc9
    CUSTOM_ASSETS_VERSION: somme-numerique-0.8.2.rc24
    ENV_NAME: somme-numerique
    HELM_CHART_NAME: demarches-simplifiees
    HELM_CHART_VERSION: 0.4.1
    HELM_REPO_NAME: adullact
    HELM_REPO_URL: ${CI_API_V4_URL}/projects/349/packages/helm/stable
    K8S_NAMESPACE: sm-production
    PATH_VALUE: somme-numerique/
    RELEASE_NAME: sm-production
    SKIP_RESTORE_STAGE: "true"
    URL_PRODUCTION: demarches-hdf.fr
